### ISSUE TITLE
Temperature scaling

### ISSUE THREAD

**Issue by ElNando888** [bad-ants-fleet/ribolands#1]
Hi, if T is expressed in Kelvins in the RT expression, then the scaling occurring at https://github.com/bad-ants-fleet/ribolands/blob/master/scripts/DrTransformer.py#L543 is probably incorrect... Granted, it must be rare that someone actually studies co-transcriptional RNA folding in extremophiles, but still...

**Comment by bad-ants-fleet** [comment]
Thanks, I fixed that!
